# Generated by Django 4.1.6 on 2023-06-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0006_socialmedia_delete_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='email_url',
            field=models.EmailField(blank=True, max_length=70),
        ),
    ]
