# Generated by Django 4.1.6 on 2023-06-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0007_alter_socialmedia_email_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='email_url',
            field=models.URLField(),
        ),
    ]
