# Generated by Django 4.1.6 on 2023-06-10 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pollapp', '0008_alter_socialmedia_email_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmedia',
            name='email_url',
        ),
    ]
