# Generated by Django 4.1.6 on 2023-06-16 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pollapp.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pollapp', '0010_pollmodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pollmodel',
            name='creator',
            field=models.ForeignKey(default=pollapp.models.get_default_creator, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
